common:
  run_label: "run_1"
  log_freq: 500
  auto_resume: true
  mixed_precision: false
dataset:
  root_train: "/home/jfaath/projects/image_data/tiny-imagenet-200/train"
  root_val: "/home/jfaath/projects/image_data/tiny-imagenet-200/val/images"
  name: "imagenet"
  category: "classification"
  train_batch_size0: 128
  val_batch_size0: 100
  eval_batch_size0: 100
  workers: 4
  persistent_workers: false
  pin_memory: true
image_augmentation:
  random_resized_crop:
    enable: true
    interpolation: "bilinear"
  random_horizontal_flip:
    enable: true
sampler:
  name: "variable_batch_sampler"
  vbs:
    crop_size_width: 64
    crop_size_height: 64
    max_n_scales: 5
    min_crop_size_width: 64
    max_crop_size_width: 96
    min_crop_size_height: 64
    max_crop_size_height: 96
    check_scale: 8
loss:
  category: "classification"
  classification:
    name: "label_smoothing"
    label_smoothing_factor: 0.1
optim:
  name: "adamw"
  weight_decay: 1.e-2
  no_decay_bn_filter_bias: false
  adamw:
    beta1: 0.9
    beta2: 0.999
scheduler:
  name: "cosine"
  is_iteration_based: false
  max_epochs: 300
  warmup_iterations: 3000
  warmup_init_lr: 0.0002
  cosine:
    max_lr: 0.002
    min_lr: 0.0002
model:
  classification:
    name: "mobilevit"
    classifier_dropout: 0.1
    mit:
      mode: "xx_small"
      ffn_dropout: 0.0
      attn_dropout: 0.0
      dropout: 0.05
      number_heads: 4
      no_fuse_local_global_features: false
      conv_kernel_size: 3
    activation:
      name: "swish"
  normalization:
    name: "batch_norm_2d"
    momentum: 0.1
  activation:
    name: "swish"
  layer:
    global_pool: "mean"
    conv_init: "kaiming_normal"
    linear_init: "trunc_normal"
    linear_init_std_dev: 0.02
ema:
  enable: true
  momentum: 0.0005
ddp:
  enable: true
  rank: 0
  world_size: -1
  dist_port: 30786
stats:
  name: [ "loss", "top1", "top5" ]
  checkpoint_metric: "top1"
  checkpoint_metric_max: true